# Generated by Django 4.2.20 on 2025-04-26 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="Customer",
            new_name="customer",
        ),
    ]
